services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: dot-env-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dotenv
      MYSQL_USER: dotenv_user
      MYSQL_PASSWORD: dotenv_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # SvelteKit Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dot-env-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://dotenv_user:dotenv_password@db:3306/dotenv
      # Add your environment variables here
      - DYNAMIC_PRIVATE_KEY=${DYNAMIC_PRIVATE_KEY:-your-private-key-here}
      - PUBLIC_DYNAMIC_KEY=${PUBLIC_DYNAMIC_KEY:-your-public-key-here}
      - STATIC_PRIVATE_KEY=${STATIC_PRIVATE_KEY:-your-static-private-key-here}
      - PUBLIC_STATIC_KEY=${PUBLIC_STATIC_KEY:-your-static-public-key-here}
      - AXIOM_TOKEN=${AXIOM_TOKEN:-}
      - AXIOM_DATASET=${AXIOM_DATASET:-}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      # Mount a volume for any persistent data if needed
      - app_data:/app/data

  # Optional: Adminer for database management
  adminer:
    image: adminer:4.8.1
    container_name: dot-env-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local
  app_data:
    driver: local

networks:
  app-network:
    driver: bridge
