apiVersion: v1
kind: Secret
metadata:
  name: dot-env-secrets
  namespace: dot-env
  labels:
    app: dot-env-sveltekit
type: Opaque
data:
  # Database credentials (base64 encoded)
  # IMPORTANT: Replace these with your own secure passwords
  # To encode: echo -n "your-secure-password" | base64

  # MySQL root password - CHANGE THIS!
  MYSQL_ROOT_PASSWORD: U3VwZXJTZWN1cmVSb290UGFzcyEyMDI0  # SuperSecureRootPass!2024

  # MySQL application user password - CHANGE THIS!
  MYSQL_PASSWORD: RG90RW52QXBwUGFzcyEyMDI0  # DotEnvAppPass!2024

  # Complete database connection URL
  DATABASE_URL: bXlzcWw6Ly9kb3RlbnZfdXNlcjpEb3RFbnZBcHBQYXNzITIwMjRAbXlzcWwtc2VydmljZTozMzA2L2RvdGVudg==  # mysql://dotenv_user:DotEnvAppPass!2024@mysql-service:3306/dotenv

  # Private API keys - REPLACE WITH YOUR ACTUAL KEYS
  # Generate secure keys: openssl rand -base64 32

  # Dynamic private key (server-side only)
  DYNAMIC_PRIVATE_KEY: WW91ckR5bmFtaWNQcml2YXRlS2V5SGVyZTEyMzQ1Ng==  # YourDynamicPrivateKeyHere123456

  # Static private key (server-side only, bundled at build time)
  STATIC_PRIVATE_KEY: WW91clN0YXRpY1ByaXZhdGVLZXlIZXJlNzg5MDEy  # YourStaticPrivateKeyHere789012

  # Axiom logging credentials - ADD YOUR ACTUAL VALUES
  # Get these from your Axiom dashboard: https://app.axiom.co/
  AXIOM_TOKEN: "xaat-443d3e51-a526-48a2-a47d-ec3fce0e24ea"  # echo -n "xaat-your-axiom-token-here" | base64
  AXIOM_DATASET: ""  # echo -n "your-dataset-name" | base64
